import BriefCaseIcon from "@/components/icons/BriefCaseIcon";
import ClipBoardIcon from "@/components/icons/ClipBoardIcon";
import UsersIcon from "@/components/icons/UsersIcon";
import SideNav from "@/components/ui/SideNav";


export const metadata = {
  title: "Employer Dashboard",
  description: "Generated by create next app",
};

const employerNavItems = [
  {
    label: "Manage Users",
    href: "/admin/users",
    icon: BriefCaseIcon,
  },
  {
    label: "Manage Jobs",
    href: "/admin/jobs",
    icon: ClipBoardIcon,
  },
  {
    label: "Settings",
    href: "/admin/settings",
    icon: UsersIcon,
  },
];

export default function AdminLayout({ children }) {
  return (
    <div className="min-h-screen flex">
      {/* Sidebar */}
      <SideNav title="Admin Panel" navItems={employerNavItems} />

      {/* Main Content */}
      <div className="flex-1 bg-gray-100 p-6">
        <main className="mt-4">{children}</main>
      </div>
    </div>
  );
}
