import BriefCaseIcon from "@/components/icons/BriefCaseIcon";
import ClipBoardIcon from "@/components/icons/ClipBoardIcon";
import UsersIcon from "@/components/icons/UsersIcon";
import SideNav from "@/components/ui/SideNav";


export const metadata = {
  title: "Employer Dashboard",
  description: "Generated by create next app",
};

const employerNavItems = [
  {
    label: "Manage Jobs",
    href: "/employer/manage-jobs",
    icon: BriefCaseIcon,
  },
,
  {
    label: "Candidates",
    href: "/employer/candidates",
    icon: UsersIcon,
  },
  {
    label: "Employer",
    href: "/employer",
    icon: UsersIcon,
  },
];

export default function EmployerLayout({ children }) {
  return (
    <div className="min-h-screen flex">
      {/* Sidebar */}
      <SideNav title="Employer Panel" navItems={employerNavItems} />

      {/* Main Content */}
      <div className="flex-1 bg-gray-100 p-6">
        <main className="mt-4">{children}</main>
      </div>
    </div>
  );
}
